services:
  server-pinus:
    image: bruce48li/cyberbullfight-server-pinus:latest
    container_name: cyberbullfight-server-pinus
    ports:
      - "3010:3010"
    networks:
      - cyberbullfight-network
  client-go:
    image: bruce48li/cyberbullfight-client-go:latest
    container_name: cyberbullfight-client-go
    environment:
      - HOST=server-pinus
      - PORT=3010
    depends_on:
      - server-pinus
    networks:
      - cyberbullfight-network

networks:
  cyberbullfight-network:
    driver: bridge